dist: trusty
language: node_js
node_js:
- "lts/*"
before_script:
- npm install
script:
- npm run deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token
  on:
    branch: master
